supported_bands:
  - 2m
  - 70cm

supported_modes:
  - [FM,FM]
  - [MOTOTRBO,DMR]
  - [FMLINK, FM Link]
  - [ECHOLINK, Echo Link]

sp_prefixy:
  - HF
  - SN
  - SO
  - SP
  - SQ
  - 3Z

sp_talk_groups:
  name: "Okręgowe grupy rozmowne"
  description: "Grupy rozmowne dla poszczególnych okręgów: <code>2601, 2602, ..., 2609</code>"
  items:
    -
      name: SP TG
      id:   260

    -
      name: SP1 TG
      id:   2601

    -
      name: SP2 TG
      id:   2602

    -
      name: SP3 TG
      id:   2603

    -
      name: SP4 TG
      id:   2604

    -
      name: SP5 TG
      id:   2605

    -
      name: SP6 TG
      id:   2606

    -
      name: SP7 TG
      id:   2607

    -
      name: SP8 TG
      id:   2608

    -
      name: SP9 TG
      id:   2609


additional_talkgroups:
  -
    name: DMR Global
    description: "Globalna grupa rozmowna"
    id:   1

  -
    name: DMR Europe
    description: "Europejska grupa rozmowna"
    id:   2

  -
    name: DMR Local
    description: "Lokalna grupa rozmowna"
    id:   9

  -
    name:        "WW English"
    description: "World Wide English"
    id:          13



additional_contacts:
  -
    name:        Echo
    description: "Papuga <code>260097</code>"
    id:          260097

  -
    name:        SP5KAB
    description: "Członkowie klubu SP5KAB zostaną dodani na początku listy (niezaleźnie od wybranych okręgów i prefiksów)"
    id:          sp5kab




sp5kab:
  - HF5JN
  - SO5GB
  - SO5GT
  - SO5WB
  - SP5AYY
  - SP5BBG
  - SP5DPD
  - SP5DRS
  - SP5DWD
  - SP5FA
  - SP5FF
  - SP5FT
  - SP5HIN
  - SP5KEI
  - SP5LMA
  - SP5MAT
  - SP5MJ
  - SP5MKL
  - SP5ML
  - SP5OSP
  - SP5OXB
  - SP5OXF
  - SP5R
  - SP5RF
  - SP5RML
  - SP5RMY
  - SP5SO
  - SP5SPS
  - SP5TA
  - SP5TZD
  - SP5UAM
  - SP5VJQ
  - SP5WIT
  - SP5WPO
  - SP5WWP
  - SP5WWY
  - SP5XOC
  - SQ3SII
  - SQ5AMR
  - SQ5ARF
  - SQ5AZQ
  - SQ5B
  - SQ5D
  - SQ5EBM
  - SQ5GN
  - SQ5IT
  - SQ5OBV
  - SQ5OBW
  - SQ5PGL
  - SQ5RJK
  - SQ5SBX
  - SQ5TDN
  - SQ5VTT
  - SQ5WLH
  - SQ5WN
  - SQ5XOV
  - SQ5ZAJ
  - SQ5ZG
  - SQ6WW
  - SQ8JMD
  - SQ8LAB
  - SQ9DEM

gov_services:
  -
    name: Metro
    freqs:
      - 154.450000
      - 154.500000
      - 154.525000
      - 415.262500
      - 415.462500
      - 425.662500
      - 425.787500
      - 425.862500
      - 425.987500
      - 426.950000

  -
    name: PKP
    freqs:
      - 150.100000
      - 150.150000
      - 150.175000
      - 150.200000
      - 150.225000
      - 150.250000
      - 150.300000
      - 150.325000
      - 150.375000
      - 150.450000
      - 150.500000
      - 150.575000
      - 154.555000


pmr:
  - 446.00625
  - 446.01875
  - 446.03125
  - 446.04375
  - 446.05625
  - 446.06875
  - 446.08125
  - 446.09375
  - 446.10625
  - 446.11875
  - 446.13125
  - 446.14375
  - 446.15625
  - 446.16875
  - 446.18125
  - 446.19375